language: ruby
sudo: false
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 1.9
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.1" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 1.9
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.2" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.0
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.1" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.0
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.2" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.1" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="3.8.5" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 1.3" FUTURE_PARSER="yes"
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.3" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 3.0"
notifications:
  email: false
